server:
  port: 8003

eureka:
  instance:
    hostname: 127.0.0.1
  server:
    enable-self-preservation: false
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  application:
    name: service-eureka

logging:
  config: I:/git_project/统一日志/log4j2-spring.xml
  file:
    path: I:/git_project/统一日志/${spring.application.name}