server:
  port: 8084

spring:
  application:
    name: rabbit-mq-consumer
#    配置mq
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: winjay
    password: 123456
    virtual-host: /
    # 发送者开启 confirm-type 确认机制 默认false
    # none值是禁用发布确认模式，是默认值
    # correlated值是发布消息成功到交换器后会触发回调方法 在2.2.0及之后
    publisher-confirm-type: correlated
    # 发送者开启 return 确认机制 默认false
    publisher-returns: true
    template:
      mandatory: true #只要消息抵达队列，以异步优先回调 returns
    listener:
      simple:
        acknowledge-mode: manual #开启消费端手动确认
